// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkPvAvBI-jGnsAOZ8Eg5Wi6oNWbfQE0E',
    appId: '1:62543235071:android:0f7857de1d1edf3b6989ca',
    messagingSenderId: '62543235071',
    projectId: 'dressmedaily-e8e0c',
    storageBucket: 'dressmedaily-e8e0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAmJ7AtpVa4GKVBByZaHSRnER2AimY81E',
    appId: '1:62543235071:ios:f20d13b39b37db3e6989ca',
    messagingSenderId: '62543235071',
    projectId: 'dressmedaily-e8e0c',
    storageBucket: 'dressmedaily-e8e0c.appspot.com',
    androidClientId: '62543235071-j2fnt56q1k1lf34o3nsn4nb3b37nl264.apps.googleusercontent.com',
    iosClientId: '62543235071-h9j0cqcaci06ma88nffla4roigjhkg7g.apps.googleusercontent.com',
    iosBundleId: 'com.sdgptest.flutterSdgp101',
  );
}
