name: Flutter CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.2'
        channel: 'stable'
    - uses: actions/setup-dart@v1
      with:
        dart-version: '3.3.0'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
